services:
  bot:
    platform: linux/x86_64
    build:
      dockerfile: Dockerfile
    depends_on:
      - postgres_bd
    restart: always
  postgres_bd:
    platform: linux/x86_64
    image: postgres:15.1-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
