"""initial

Revision ID: d903460bf7ea
Revises:
Create Date: 2024-07-18 15:08:19.840801

"""
from typing import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd903460bf7ea'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('models',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('count_of_params', sa.Integer(), nullable=False),
                    sa.Column('type', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('subscriptions',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('description', sa.String(), nullable=False),
                    sa.Column('price', sa.Double(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('users',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('subscription_id', sa.Integer(), nullable=False),
                    sa.Column('username', sa.String(), nullable=False),
                    sa.Column('main_name', sa.String(), nullable=False),
                    sa.Column('language', sa.String(), nullable=False),
                    sa.Column('balance', sa.Double(), nullable=False),
                    sa.Column('registration_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
                    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('activities',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('date_time', sa.DateTime(), server_default=sa.text('CURRENT_DATE'), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('model_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('payments_history',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('subscription_id', sa.Integer(), nullable=False),
                    sa.Column('paid', sa.Double(), nullable=False),
                    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payments_history')
    op.drop_table('activities')
    op.drop_table('users')
    op.drop_table('subscriptions')
    op.drop_table('models')
    # ### end Alembic commands ###
